spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQBzTXGePo0WdkHpKi66Wh/DWrIU8AY4IWqaEHYUm65FUHnWwFDqtDSo6whcBlrjrXGQhHtXVxqqhqYldC7pKnnzUIM9IQxqBKps01HiWtO/xHM/uDN3pwDDJa0RvaBgOPU7d8OxZX4qM76qsBXVPuU+HCU3tad4eNw7Ek8IwUvXclelV8Sc8rzWdf8jjLKWXUXT3qbN2X1dKvBWTd3mnZDxDG35lz1qDSTIMvcRhNUjH+L5m23m6mDgmwS2aN3S0NmcQkAJg3Nj54gXVFaqQy2LdIgAvXXx2zrIopjltaOuxB0rxtMqy9BO2fsEdAJ+gqyK3kESXfXbUzbNGAlcu5XYb1iopj6HeuFid8gpYZrJzR19YOzPuErft5w6N4Ed1Vg="

token:
  expiration_time: 864000000
  secret: "{cipher}AQCK9AIqL95F5WAomfq7S8TpmQkLAXmEj8bJHaUdFo+FWdEl2G79L4G3tumE0xy71RI2XNmjPImig6Dmd+QwO35Eem40b98w6DuOkgkwdrBxK3SI2vZXg3rhw4/6N9JtFUCMsqDyHVZRjeOilo1D9G5WKkJQ4AZNPNsu+/qy7xE++T8YGzh1m6CfGjTCO94Ytch/OaDJ0AJ+XIcRbIaXo9pTao0M6akahnUFkLzB0civE2MbGvdCdrH91HWG6unAVdDQr2UNoki/CTim3YiecaGw/n+Fpe/kzc+KJuZ/zq1KBqttzmjDjrXLYUXaPoMbSitMuQP8CQ88jUt1R/YTHhwqRN512vuHqpnHDKmki8W++WZiWWwx98dubvMfaxMd/6GqloEHSaGIpFk9879GBnCI"

gateway:
  ip: 192.168.0.7

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: User's orders is empty
